const GET_PROFILE_REQUEST="GET_PROFILE_REQUEST";
const GET_PROFILE_SUCCESS ="GET_PROFILE_SUCCESS";
const GET_PROFILE_FAILURE ="GET_PROFILE_FAILURE";

const CHANGE_GENERAL_INFO_INPUT ="CHANGE_GENERAL_INFO_INPUT"

export{GET_PROFILE_REQUEST ,GET_PROFILE_SUCCESS,GET_PROFILE_FAILURE ,CHANGE_GENERAL_INFO_INPUT}