const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST"
const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE"

const CLEAR_PROFILE_RESPONSE = "CLEAR_PROFILE_RESPONSE"

const CHANGE_GENERAL_INFO_INPUT = "CHANGE_GENERAL_INFO_INPUT"

const CHANGE_BASIC_INFO_INPUT = "CHANGE_BASIC_INFO_INPUT"

const UPDATE_ADDITIONAL_INFO_REQUEST = "UPDATE_ADDITIONAL_INFO_REQUEST";
const UPDATE_ADDITIONAL_INFO_SUCCESS = "UPDATE_ADDITIONAL_INFO_SUCCESS";
const UPDATE_ADDITIONAL_INFO_FAILURE = "UPDATE_ADDITIONAL_INFO_FAILURE";

const CLEAR_UPDATE_INFO_RESPONSE = "CLEAR_UPDATE_INFO_RESPONSE";

const LANGUAGE_LIST_REQUEST = "LANGUAGE_LIST_REQUEST";
const LANGUAGE_LIST_SUCCESS = "LANGUAGE_LIST_SUCCESS";
const LANGUAGE_LIST_FAILURE = "LANGUAGE_LIST_FAILURE";

const SKILLS_LIST_REQUEST = "SKILLS_LIST_REQUEST";
const SKILLS_LIST_SUCCESS = "SKILLS_LIST_SUCCESS";
const SKILLS_LIST_FAILURE = "SKILLS_LIST_FAILURE";

/**
 * projects constants
 */
const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST"
const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS"
const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE"

const ADD_NEW_PROJECT = "ADD_NEW_PROJECT"

const CHANGE_MY_PROJECT_DETAIL_INFO = "CHANGE_MY_PROJECT_DETAIL_INFO"

const SAVE_MY_PROJECTS_REQUEST = "SAVE_MY_PROJECTS_REQUEST";
const SAVE_MY_PROJECTS_SUCCESS = "SAVE_MY_PROJECTS_SUCCESS";
const SAVE_MY_PROJECTS_FAILURE = "SAVE_MY_PROJECTS_FAILURE";

const CLEAR_SAVE_MY_PROJECTS_RESPONSE = "CLEAR_SAVE_MY_PROJECTS_RESPONSE";

const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";

const CLEAR_DELETE_PROJECT_RESPONSE = "CLEAR_DELETE_PROJECT_RESPONSE"

const CHANGE_EDIT_PROJECT = "CHANGE_EDIT_PROJECT"

const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";
const CHANGE_SOCIAL_ICON_INPUT = "CHANGE_SOCIAL_ICON_INPUT"

const ADD_SOCIAL_ICON_REQUEST = "ADD_SOCIAL_ICON_REQUEST";
const ADD_SOCIAL_ICON_SUCCESS = "ADD_SOCIAL_ICON_SUCCESS";
const ADD_SOCIAL_ICON_FAILURE = "ADD_SOCIAL_ICON_FAILURE";

const CLEAR_ADD_SOCIAL_RESPONSE ="CLEAR_ADD_SOCIAL_RESPONSE";

const GET_SOCIAL_ICON_REQUEST = "GET_SOCIAL_ICON_REQUEST";
const GET_SOCIAL_ICON_SUCCESS = "GET_SOCIAL_ICON_SUCCESS";
const GET_SOCIAL_ICON_FAILURE = "GET_SOCIAL_ICON_FAILURE";

const CLEAR_UPDATE_PROJECT_RESPONSE = "CLEAR_UPDATE_PROJECT_RESPONSE"


/**
 * employment constants
 */

 const GET_EMPLOYMENTS_REQUEST = "GET_EMPLOYMENTS_REQUEST"
 const GET_EMPLOYMENTS_SUCCESS = "GET_EMPLOYMENTS_SUCCESS"
 const GET_EMPLOYMENTS_FAILURE = "GET_EMPLOYMENTS_FAILURE"
 
 const ADD_NEW_EMPLOYMENT = "ADD_NEW_EMPLOYMENT"
 
 const CHANGE_MY_EMPLOYMENT_DETAIL_INFO = "CHANGE_MY_EMPLOYMENT_DETAIL_INFO"
 
 const SAVE_MY_EMPLOYMENTS_REQUEST = "SAVE_MY_EMPLOYMENTS_REQUEST";
 const SAVE_MY_EMPLOYMENTS_SUCCESS = "SAVE_MY_EMPLOYMENTS_SUCCESS";
 const SAVE_MY_EMPLOYMENTS_FAILURE = "SAVE_MY_EMPLOYMENTS_FAILURE";
 
 const CLEAR_SAVE_MY_EMPLOYMENTS_RESPONSE = "CLEAR_SAVE_MY_EMPLOYMENTS_RESPONSE";
 
 const DELETE_EMPLOYMENT_REQUEST = "DELETE_EMPLOYMENT_REQUEST";
 const DELETE_EMPLOYMENT_SUCCESS = "DELETE_EMPLOYMENT_SUCCESS";
 const DELETE_EMPLOYMENT_FAILURE = "DELETE_EMPLOYMENT_FAILURE";
 
 const CLEAR_DELETE_EMPLOYMENT_RESPONSE = "CLEAR_DELETE_EMPLOYMENT_RESPONSE"
 
 const CHANGE_EDIT_EMPLOYMENT = "CHANGE_EDIT_EMPLOYMENT"
 
 const UPDATE_EMPLOYMENT_REQUEST = "UPDATE_EMPLOYMENT_REQUEST";
 const UPDATE_EMPLOYMENT_SUCCESS = "UPDATE_EMPLOYMENT_SUCCESS";
 const UPDATE_EMPLOYMENT_FAILURE = "UPDATE_EMPLOYMENT_FAILURE";
 
 const CLEAR_UPDATE_EMPLOYMENT_RESPONSE = "CLEAR_UPDATE_EMPLOYMENT_RESPONSE"


export {
    UPDATE_ADDITIONAL_INFO_REQUEST, UPDATE_ADDITIONAL_INFO_SUCCESS, UPDATE_ADDITIONAL_INFO_FAILURE,
    CLEAR_UPDATE_INFO_RESPONSE,
    LANGUAGE_LIST_REQUEST, LANGUAGE_LIST_SUCCESS, LANGUAGE_LIST_FAILURE,
    SKILLS_LIST_REQUEST, SKILLS_LIST_SUCCESS, SKILLS_LIST_FAILURE,

    GET_PROFILE_REQUEST, GET_PROFILE_SUCCESS, GET_PROFILE_FAILURE,
    CLEAR_PROFILE_RESPONSE,
    CHANGE_GENERAL_INFO_INPUT,
    CHANGE_BASIC_INFO_INPUT,

    GET_PROJECTS_REQUEST, GET_PROJECTS_SUCCESS, GET_PROJECTS_FAILURE,
    ADD_NEW_PROJECT,
    CHANGE_MY_PROJECT_DETAIL_INFO,
    SAVE_MY_PROJECTS_REQUEST, SAVE_MY_PROJECTS_SUCCESS, SAVE_MY_PROJECTS_FAILURE,
    CLEAR_SAVE_MY_PROJECTS_RESPONSE,
    DELETE_PROJECT_REQUEST, DELETE_PROJECT_SUCCESS, DELETE_PROJECT_FAILURE,
    CLEAR_DELETE_PROJECT_RESPONSE,
    CHANGE_EDIT_PROJECT,
    UPDATE_PROJECT_REQUEST, UPDATE_PROJECT_SUCCESS, UPDATE_PROJECT_FAILURE,
    CLEAR_UPDATE_PROJECT_RESPONSE,

    GET_EMPLOYMENTS_REQUEST, GET_EMPLOYMENTS_SUCCESS, GET_EMPLOYMENTS_FAILURE,
    ADD_NEW_EMPLOYMENT,
    CHANGE_MY_EMPLOYMENT_DETAIL_INFO,
    SAVE_MY_EMPLOYMENTS_REQUEST, SAVE_MY_EMPLOYMENTS_SUCCESS, SAVE_MY_EMPLOYMENTS_FAILURE,
    CLEAR_SAVE_MY_EMPLOYMENTS_RESPONSE,
    DELETE_EMPLOYMENT_REQUEST, DELETE_EMPLOYMENT_SUCCESS, DELETE_EMPLOYMENT_FAILURE,
    CLEAR_DELETE_EMPLOYMENT_RESPONSE,
    CHANGE_EDIT_EMPLOYMENT,
    UPDATE_EMPLOYMENT_REQUEST, UPDATE_EMPLOYMENT_SUCCESS, UPDATE_EMPLOYMENT_FAILURE,
    CLEAR_UPDATE_EMPLOYMENT_RESPONSE,

    ADD_SOCIAL_ICON_REQUEST,ADD_SOCIAL_ICON_SUCCESS,ADD_SOCIAL_ICON_FAILURE ,
    GET_SOCIAL_ICON_REQUEST ,GET_SOCIAL_ICON_SUCCESS , GET_SOCIAL_ICON_FAILURE ,CHANGE_SOCIAL_ICON_INPUT,
    CLEAR_ADD_SOCIAL_RESPONSE
}
