const INVITE_MODEL_INPUT = "INVITE_MODEL_INPUT"

const INVITE_DATA_REQUEST="INVITE_DATA_REQUEST";
const INVITE_DATA_SUCCESS ="INVITE_DATA_SUCCESS";
const INVITE_DATA_FAILURE ="INVITE_DATA_FAILURE";

const CLEAR_INVITE_RESPONSE = "CLEAR_INVITE_RESPONSE"

export{INVITE_MODEL_INPUT, INVITE_DATA_REQUEST ,INVITE_DATA_SUCCESS,INVITE_DATA_FAILURE ,CLEAR_INVITE_RESPONSE}