const INVITE_MODEL_INPUT = "INVITE_MODEL_INPUT"

const INVITE_DATA_REQUEST = "INVITE_DATA_REQUEST";
const INVITE_DATA_SUCCESS = "INVITE_DATA_SUCCESS";
const INVITE_DATA_FAILURE = "INVITE_DATA_FAILURE";

const CLEAR_INVITE_RESPONSE = "CLEAR_INVITE_RESPONSE"

const CHANGE_SHARE_INPUT = "CHANGE_SHARE_INPUT"

const POST_UPLOAD_REQUEST = "POST_UPLOAD_REQUEST";
const POST_UPLOAD_SUCCESS = "POST_UPLOAD_SUCCESS";
const POST_UPLOAD_FAILURE = "POST_UPLOAD_FAILURE";

const CLEAR_POST_UPLOAD_RESPONSE = "CLEAR_POST_UPLOAD_RESPONSE";

const GET_POST_REQUEST = "GET_POST_REQUEST";
const GET_POST_SUCCESS = "GET_POST_SUCCESS";
const GET_POST_FAILURE = "GET_POST_FAILURE";

const CLEAR_GET_POST_RESPONSE = "CLEAR_GET_POST_RESPONSE"

const CHANGE_ACTIVA_CAROUSAL = "CHANGE_ACTIVA_CAROUSAL"

const CHANGE_ALL_POST_DETAIL ="CHANGE_ALL_POST_DETAIL"

const LIKE_DISLIKE_POST_DATA_REQUEST = "LIKE_DISLIKE_POST_DATA_REQUEST";
const LIKE_DISLIKE_POST_DATA_SUCCESS = "LIKE_DISLIKE_POST_DATA_SUCCESS";
const LIKE_DISLIKE_POST_DATA_FAILURE = "LIKE_DISLIKE_POST_DATA_FAILURE";

export {
    INVITE_MODEL_INPUT, INVITE_DATA_REQUEST, INVITE_DATA_SUCCESS, INVITE_DATA_FAILURE, CLEAR_INVITE_RESPONSE, CHANGE_SHARE_INPUT,
    POST_UPLOAD_REQUEST, POST_UPLOAD_SUCCESS, POST_UPLOAD_FAILURE, CLEAR_POST_UPLOAD_RESPONSE, GET_POST_REQUEST,
    GET_POST_SUCCESS, GET_POST_FAILURE, CLEAR_GET_POST_RESPONSE, CHANGE_ACTIVA_CAROUSAL ,CHANGE_ALL_POST_DETAIL,
    LIKE_DISLIKE_POST_DATA_REQUEST,LIKE_DISLIKE_POST_DATA_SUCCESS,LIKE_DISLIKE_POST_DATA_FAILURE
}